// Code generated by cmd/module/gen. DO NOT EDIT.
package modules

import (
	authorizationModule "github.com/dinhtp/lee-goo/modules/authorization/fx"
	coreModule "github.com/dinhtp/lee-goo/modules/core/fx"
	userModule "github.com/dinhtp/lee-goo/modules/user/fx"

	"github.com/dinhtp/lee-goo/system/migrator"
)

// Registry returns all registered module migration sources, keyed by module name.
// Run `make generate` to refresh after adding a module.
func Registry() map[string]migrator.Source {
	return map[string]migrator.Source{
		"authorization": authorizationModule.Source(),
		"core":          coreModule.Source(),
		"user":          userModule.Source(),
	}
}
